//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Partners_product = new HashSet<Partners_product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<double> Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
        public Nullable<int> ID_material { get; set; }
    
        public virtual Material_type Material_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners_product> Partners_product { get; set; }
        public virtual Product_type Product_type { get; set; }
    }
}
