//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestBaseEntities1 : DbContext
    {
        public TestBaseEntities1()
            : base("name=TestBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material_type> Material_type { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Partners_product> Partners_product { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_type> Product_type { get; set; }
    }
}
